// Package apidocs Code generated by swaggo/swag. DO NOT EDIT
package apidocs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/init": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Initialize administrator account",
                "parameters": [
                    {
                        "description": "Admin credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.InitAdminRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/auth.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login as administrator",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/auth.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout administrator session",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get currently authenticated user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/auth.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            }
        },
        "/auth/status": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get system initialization status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/auth.AuthStatusResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/cameras": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "camera"
                ],
                "summary": "List cameras",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pagination limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "camera"
                ],
                "summary": "Create a new camera",
                "parameters": [
                    {
                        "description": "Camera parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/camera.CreateCameraRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/camera.CameraResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            }
        },
        "/cameras/events": {
            "get": {
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "camera"
                ],
                "summary": "Subscribe to camera state events via SSE",
                "responses": {
                    "200": {
                        "description": "Server-Sent Events stream",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/cameras/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "camera"
                ],
                "summary": "Get camera by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Camera ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/camera.CameraResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "camera"
                ],
                "summary": "Update camera configuration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Camera ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/camera.UpdateCameraRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/camera.CameraResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "camera"
                ],
                "summary": "Delete camera",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Camera ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            }
        },
        "/cameras/{id}/credentials": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "camera"
                ],
                "summary": "Get camera plaintext credentials",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Camera ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/camera.CameraCredentialsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            }
        },
        "/cameras/{id}/diagnose": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "camera"
                ],
                "summary": "Manually diagnose camera connection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Camera ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/camera.DiagnoseResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            }
        },
        "/cameras/{id}/streams/{role}/ws": {
            "get": {
                "tags": [
                    "camera"
                ],
                "summary": "WebSocket 视频流实时预览",
                "parameters": [
                    {
                        "type": "string",
                        "description": "摄像机 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "码流类型 (main 或 sub，默认 main)",
                        "name": "role",
                        "in": "path"
                    }
                ],
                "responses": {}
            }
        },
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Get host health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/app.HealthData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.HealthData": {
            "type": "object",
            "properties": {
                "components": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "auth.AuthStatusResponse": {
            "type": "object",
            "properties": {
                "initialized": {
                    "type": "boolean"
                }
            }
        },
        "auth.InitAdminRequest": {
            "type": "object",
            "required": [
                "confirmPassword",
                "password",
                "username"
            ],
            "properties": {
                "confirmPassword": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 8
                },
                "username": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 3
                }
            }
        },
        "auth.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "auth.UserResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "camera.CameraCredentialsResponse": {
            "type": "object",
            "properties": {
                "cameraId": {
                    "type": "string"
                },
                "credentials": {
                    "description": "role -\u003e full plaintext RTSP URL",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "camera.CameraResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "degraded": {
                    "type": "boolean"
                },
                "enabled": {
                    "type": "boolean"
                },
                "health": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastCheckedAt": {
                    "type": "string"
                },
                "lastSuccessAt": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "revision": {
                    "type": "integer"
                },
                "session": {
                    "type": "string"
                },
                "stale": {
                    "type": "boolean"
                },
                "streams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/camera.StreamResponse"
                    }
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "camera.CameraStateInfo": {
            "type": "object",
            "properties": {
                "cameraId": {
                    "type": "string"
                },
                "degraded": {
                    "type": "boolean"
                },
                "enabled": {
                    "type": "boolean"
                },
                "health": {
                    "type": "string"
                },
                "lastCheckedAt": {
                    "type": "string"
                },
                "lastSuccessAt": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "revision": {
                    "type": "integer"
                },
                "session": {
                    "type": "string"
                },
                "stale": {
                    "type": "boolean"
                },
                "streams": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/camera.StreamStateInfo"
                    }
                }
            }
        },
        "camera.CreateCameraRequest": {
            "type": "object",
            "required": [
                "mainStream",
                "name"
            ],
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "mainStream": {
                    "$ref": "#/definitions/camera.CreateStreamRequest"
                },
                "name": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1
                },
                "subStream": {
                    "$ref": "#/definitions/camera.CreateStreamRequest"
                }
            }
        },
        "camera.CreateStreamRequest": {
            "type": "object",
            "required": [
                "rtspUrl"
            ],
            "properties": {
                "protocol": {
                    "description": "\"rtsp\" (default)",
                    "type": "string"
                },
                "role": {
                    "description": "\"main\" or \"sub\"",
                    "type": "string"
                },
                "rtspUrl": {
                    "type": "string"
                },
                "transport": {
                    "description": "\"tcp\" or \"udp\" (default \"tcp\")",
                    "type": "string"
                }
            }
        },
        "camera.DiagnoseResponse": {
            "type": "object",
            "properties": {
                "cameraId": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "state": {
                    "$ref": "#/definitions/camera.CameraStateInfo"
                }
            }
        },
        "camera.StreamResponse": {
            "type": "object",
            "properties": {
                "codec": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "fps": {
                    "type": "number"
                },
                "fpsString": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "protocol": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "rtspUrl": {
                    "description": "Complete RTSP URL for frontend playback and display",
                    "type": "string"
                },
                "runtimeState": {
                    "$ref": "#/definitions/camera.StreamStateInfo"
                },
                "transport": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "camera.StreamStateInfo": {
            "type": "object",
            "properties": {
                "consecutiveFailures": {
                    "type": "integer"
                },
                "errorMessage": {
                    "type": "string"
                },
                "evidenceType": {
                    "type": "string"
                },
                "health": {
                    "type": "string"
                },
                "lastCheckedAt": {
                    "type": "string"
                },
                "lastSuccessAt": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "session": {
                    "type": "string"
                }
            }
        },
        "camera.UpdateCameraRequest": {
            "type": "object",
            "required": [
                "revision"
            ],
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "mainStream": {
                    "$ref": "#/definitions/camera.CreateStreamRequest"
                },
                "name": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1
                },
                "revision": {
                    "type": "integer"
                },
                "subStream": {
                    "$ref": "#/definitions/camera.CreateStreamRequest"
                }
            }
        },
        "httputil.FieldDetail": {
            "type": "object",
            "required": [
                "code",
                "field",
                "message"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "httputil.Response": {
            "type": "object",
            "required": [
                "code",
                "data",
                "message"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {},
                "details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/httputil.FieldDetail"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Zhulong API",
	Description:      "Local API for the Zhulong edge operations host.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
