// Package apidocs Code generated by swaggo/swag. DO NOT EDIT
package apidocs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/audit/logs": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audit"
                ],
                "summary": "List audit logs with filtering and pagination",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (1-based, default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default 20, max 100)",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by one action (legacy parameter)",
                        "name": "action",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "Filter by any matching action (repeat parameter for multiple values)",
                        "name": "actions",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by status (success/failed)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start time (RFC3339)",
                        "name": "startTime",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time (RFC3339)",
                        "name": "endTime",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/httputil.PaginatedData-audit_AuditLogDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audit"
                ],
                "summary": "Clear audit logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Clear logs older than this RFC3339 timestamp",
                        "name": "before",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/auth/init": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Initialize administrator account",
                "parameters": [
                    {
                        "description": "Admin credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.InitAdminRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/auth.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login as administrator",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/auth.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout administrator session",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get currently authenticated user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/auth.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            }
        },
        "/auth/status": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get system initialization status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/auth.AuthStatusResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/cameras": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "camera"
                ],
                "summary": "List cameras",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (1-based, default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default 20, max 100)",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Legacy pagination limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Legacy pagination offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/httputil.PaginatedData-camera_CameraResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "camera"
                ],
                "summary": "Create a new camera",
                "parameters": [
                    {
                        "description": "Camera parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/camera.CreateCameraRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/camera.CameraResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            }
        },
        "/cameras/events": {
            "get": {
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "camera"
                ],
                "summary": "Subscribe to camera state events via SSE",
                "responses": {
                    "200": {
                        "description": "Server-Sent Events stream",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/cameras/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "camera"
                ],
                "summary": "Get camera by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Camera ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/camera.CameraResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "camera"
                ],
                "summary": "Update camera configuration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Camera ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/camera.UpdateCameraRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/camera.CameraResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "camera"
                ],
                "summary": "Delete camera",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Camera ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            }
        },
        "/cameras/{id}/credentials": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "camera"
                ],
                "summary": "Get camera plaintext credentials",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Camera ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/camera.CameraCredentialsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            }
        },
        "/cameras/{id}/diagnose": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "camera"
                ],
                "summary": "Manually diagnose camera connection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Camera ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/camera.DiagnoseResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            }
        },
        "/cameras/{id}/streams/{role}/ws": {
            "get": {
                "tags": [
                    "camera"
                ],
                "summary": "WebSocket 视频流实时预览",
                "parameters": [
                    {
                        "type": "string",
                        "description": "摄像机 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "码流类型 (main 或 sub，默认 main)",
                        "name": "role",
                        "in": "path"
                    }
                ],
                "responses": {}
            }
        },
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Get host health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/app.HealthData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            }
        },
        "/system/network/confirm": {
            "post": {
                "description": "Solidifies current trial configuration and disarms the watchdog timer. Accepts session authentication or one-time confirmation token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "network"
                ],
                "summary": "Confirm network trial configuration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Confirmation token",
                        "name": "token",
                        "in": "query"
                    },
                    {
                        "description": "Confirmation token payload",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/network.ConfirmRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            }
        },
        "/system/network/interfaces": {
            "get": {
                "description": "Queries physical network interfaces, marking the current session interface only when it can be identified unambiguously.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "network"
                ],
                "summary": "List physical network interfaces",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/network.InterfaceInfo"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            }
        },
        "/system/network/interfaces/{name}/apply": {
            "post": {
                "description": "Arms a two-phase watchdog transaction, returns a confirmation token and starts delayed reconfiguration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "network"
                ],
                "summary": "Apply interface configuration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Interface identifier, e.g. eth0",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Configuration payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/network.InterfaceConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/network.ApplyResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            }
        },
        "/system/network/ping": {
            "post": {
                "description": "Performs lightweight ICMP/TCP ping probe against gateway or IP address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "network"
                ],
                "summary": "Probe network target connectivity",
                "parameters": [
                    {
                        "description": "Ping request payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/network.PingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/network.PingResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            }
        },
        "/system/network/rollback": {
            "post": {
                "description": "Immediately cancels trial configuration and restores previous safe state. Accepts session authentication or one-time confirmation token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "network"
                ],
                "summary": "Rollback network trial configuration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Confirmation token",
                        "name": "token",
                        "in": "query"
                    },
                    {
                        "description": "Rollback payload",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/network.RollbackRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            }
        },
        "/system/network/status": {
            "get": {
                "description": "Returns active watchdog transaction state if a network trial is currently running",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "network"
                ],
                "summary": "Get active network transaction status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/network.TransactionState"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/system/storage/cleanup": {
            "post": {
                "description": "Forces an immediate pruning cycle across expired exports and recordings according to lifecycle policy.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Manually trigger storage prune cycle",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/storage.CleanupSummary"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            }
        },
        "/system/storage/config": {
            "get": {
                "description": "Retrieves current media root directory, retention periods, and watermark thresholds.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Get media storage lifecycle configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/storage.StorageConfig"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "Validates and updates media root directory, retention policies, and high/low watermarks with live hot switching.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Update media storage lifecycle configuration",
                "parameters": [
                    {
                        "description": "Storage configuration parameters",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/storage.UpdateConfigRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/storage.StorageStatus"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            }
        },
        "/system/storage/status": {
            "get": {
                "description": "Retrieves disk capacity metrics, categorized usage breakdown, mount point, and current health status.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Get media storage status and volume telemetry",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/storage.StorageStatus"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            }
        },
        "/system/storage/test": {
            "post": {
                "description": "Performs write probe, filesystem detection, and external volume identity verification on candidate path.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Test candidate storage directory",
                "parameters": [
                    {
                        "description": "Target directory path to test",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/storage.PathTestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/storage.PathTestResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            }
        },
        "/system/time": {
            "get": {
                "description": "Retrieves current kernel time, active timezone, NTP candidate servers, synchronization state, and hardware RTC status.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Get system time status and clock health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/systemtime.SystemTimeStatus"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            }
        },
        "/system/time/config": {
            "put": {
                "description": "Updates synchronization mode (ntp/manual), NTP server pool, polling interval, and system IANA timezone.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Update system time configuration",
                "parameters": [
                    {
                        "description": "Time configuration parameters",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/systemtime.UpdateConfigRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/systemtime.SystemTimeStatus"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            }
        },
        "/system/time/manual": {
            "post": {
                "description": "Explicitly sets kernel CLOCK_REALTIME and commits new time to hardware RTC chip.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Manually set system clock or synchronize browser time",
                "parameters": [
                    {
                        "description": "Target ISO-8601 or RFC3339 timestamp",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/systemtime.ManualTimeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/systemtime.SystemTimeStatus"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            }
        },
        "/system/time/sync": {
            "post": {
                "description": "Forces an immediate NTP query and clock alignment attempt against configured NTP server pool.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Trigger immediate NTP synchronization",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httputil.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/systemtime.SystemTimeStatus"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httputil.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.HealthData": {
            "type": "object",
            "properties": {
                "components": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "audit.AuditLogDTO": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "detail": {
                    "type": "string"
                },
                "errorMsg": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ip": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "auth.AuthStatusResponse": {
            "type": "object",
            "properties": {
                "initialized": {
                    "type": "boolean"
                }
            }
        },
        "auth.InitAdminRequest": {
            "type": "object",
            "required": [
                "confirmPassword",
                "password",
                "username"
            ],
            "properties": {
                "confirmPassword": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 8
                },
                "username": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 3
                }
            }
        },
        "auth.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "auth.UserResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "camera.CameraCredentialsResponse": {
            "type": "object",
            "properties": {
                "cameraId": {
                    "type": "string"
                },
                "credentials": {
                    "description": "role -\u003e full plaintext RTSP URL",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "camera.CameraResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "degraded": {
                    "type": "boolean"
                },
                "enabled": {
                    "type": "boolean"
                },
                "health": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastCheckedAt": {
                    "type": "string"
                },
                "lastSuccessAt": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "revision": {
                    "type": "integer"
                },
                "session": {
                    "type": "string"
                },
                "stale": {
                    "type": "boolean"
                },
                "streams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/camera.StreamResponse"
                    }
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "camera.CameraStateInfo": {
            "type": "object",
            "properties": {
                "cameraId": {
                    "type": "string"
                },
                "degraded": {
                    "type": "boolean"
                },
                "enabled": {
                    "type": "boolean"
                },
                "health": {
                    "type": "string"
                },
                "lastCheckedAt": {
                    "type": "string"
                },
                "lastSuccessAt": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "revision": {
                    "type": "integer"
                },
                "session": {
                    "type": "string"
                },
                "stale": {
                    "type": "boolean"
                },
                "streams": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/camera.StreamStateInfo"
                    }
                }
            }
        },
        "camera.CreateCameraRequest": {
            "type": "object",
            "required": [
                "mainStream",
                "name"
            ],
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "mainStream": {
                    "$ref": "#/definitions/camera.CreateStreamRequest"
                },
                "name": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1
                },
                "subStream": {
                    "$ref": "#/definitions/camera.CreateStreamRequest"
                }
            }
        },
        "camera.CreateStreamRequest": {
            "type": "object",
            "required": [
                "rtspUrl"
            ],
            "properties": {
                "protocol": {
                    "description": "\"rtsp\" (default)",
                    "type": "string"
                },
                "role": {
                    "description": "\"main\" or \"sub\"",
                    "type": "string"
                },
                "rtspUrl": {
                    "type": "string"
                },
                "transport": {
                    "description": "\"tcp\" or \"udp\" (default \"tcp\")",
                    "type": "string"
                }
            }
        },
        "camera.DiagnoseResponse": {
            "type": "object",
            "properties": {
                "cameraId": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "state": {
                    "$ref": "#/definitions/camera.CameraStateInfo"
                }
            }
        },
        "camera.StreamResponse": {
            "type": "object",
            "properties": {
                "codec": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "fps": {
                    "type": "number"
                },
                "fpsString": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "protocol": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "rtspUrl": {
                    "description": "Complete RTSP URL for frontend playback and display",
                    "type": "string"
                },
                "runtimeState": {
                    "$ref": "#/definitions/camera.StreamStateInfo"
                },
                "transport": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "camera.StreamStateInfo": {
            "type": "object",
            "properties": {
                "consecutiveFailures": {
                    "type": "integer"
                },
                "errorMessage": {
                    "type": "string"
                },
                "evidenceType": {
                    "type": "string"
                },
                "health": {
                    "type": "string"
                },
                "lastCheckedAt": {
                    "type": "string"
                },
                "lastSuccessAt": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "session": {
                    "type": "string"
                }
            }
        },
        "camera.UpdateCameraRequest": {
            "type": "object",
            "required": [
                "revision"
            ],
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "mainStream": {
                    "$ref": "#/definitions/camera.CreateStreamRequest"
                },
                "name": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1
                },
                "revision": {
                    "type": "integer"
                },
                "subStream": {
                    "$ref": "#/definitions/camera.CreateStreamRequest"
                }
            }
        },
        "httputil.FieldDetail": {
            "type": "object",
            "required": [
                "code",
                "field",
                "message"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "httputil.PaginatedData-audit_AuditLogDTO": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/audit.AuditLogDTO"
                    }
                },
                "limit": {
                    "description": "Backwards compatibility fields for legacy clients expecting limit/offset",
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "httputil.PaginatedData-camera_CameraResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/camera.CameraResponse"
                    }
                },
                "limit": {
                    "description": "Backwards compatibility fields for legacy clients expecting limit/offset",
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "httputil.Response": {
            "type": "object",
            "required": [
                "code",
                "data",
                "message"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {},
                "details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/httputil.FieldDetail"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "network.ApplyResponse": {
            "type": "object",
            "properties": {
                "confirmToken": {
                    "type": "string"
                },
                "targetUrl": {
                    "type": "string"
                },
                "timeoutSec": {
                    "type": "integer"
                },
                "transactionId": {
                    "type": "string"
                }
            }
        },
        "network.ConfirmRequest": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "network.InterfaceConfig": {
            "type": "object",
            "required": [
                "mode"
            ],
            "properties": {
                "dns": {
                    "description": "DNS servers list",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "gateway": {
                    "description": "Optional gateway address, e.g. \"192.168.1.1\"",
                    "type": "string"
                },
                "ipAddress": {
                    "description": "Required when mode is \"static\", e.g. \"192.168.1.100\"",
                    "type": "string"
                },
                "mode": {
                    "type": "string",
                    "enum": [
                        "dhcp",
                        "static"
                    ]
                },
                "setDefault": {
                    "description": "Designate this interface as default gateway",
                    "type": "boolean"
                },
                "subnetMask": {
                    "description": "Required when mode is \"static\", e.g. \"255.255.255.0\"",
                    "type": "string"
                }
            }
        },
        "network.InterfaceInfo": {
            "type": "object",
            "properties": {
                "dns": {
                    "description": "Configured DNS servers",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "gateway": {
                    "description": "Configured gateway address, or empty",
                    "type": "string"
                },
                "ipAddresses": {
                    "description": "Assigned IPv4 addresses with CIDR prefix, e.g. [\"192.168.1.100/24\"]",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "isCurrent": {
                    "description": "True only when the current HTTP request maps unambiguously to this interface",
                    "type": "boolean"
                },
                "isDefaultGw": {
                    "description": "True if interface hosts default route (0.0.0.0/0)",
                    "type": "boolean"
                },
                "linkUp": {
                    "description": "Carrier status (cable plugged in)",
                    "type": "boolean"
                },
                "mac": {
                    "description": "Physical MAC address, e.g. \"52:54:00:12:34:56\"",
                    "type": "string"
                },
                "mode": {
                    "description": "\"dhcp\" or \"static\"",
                    "type": "string"
                },
                "name": {
                    "description": "Interface identifier, e.g. \"eth0\"",
                    "type": "string"
                }
            }
        },
        "network.PingRequest": {
            "type": "object",
            "required": [
                "target"
            ],
            "properties": {
                "target": {
                    "type": "string"
                }
            }
        },
        "network.PingResponse": {
            "type": "object",
            "properties": {
                "reachable": {
                    "type": "boolean"
                },
                "rttMs": {
                    "type": "number"
                }
            }
        },
        "network.RollbackRequest": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "network.TransactionState": {
            "type": "object",
            "properties": {
                "confirmToken": {
                    "type": "string"
                },
                "expiresAt": {
                    "type": "string"
                },
                "interfaceName": {
                    "type": "string"
                },
                "rollbackConfig": {
                    "$ref": "#/definitions/network.InterfaceConfig"
                },
                "status": {
                    "description": "\"idle\", \"pending_confirm\", \"rolling_back\"",
                    "type": "string"
                },
                "targetUrl": {
                    "type": "string"
                },
                "timeoutSec": {
                    "type": "integer"
                },
                "transactionId": {
                    "type": "string"
                }
            }
        },
        "storage.CleanupSummary": {
            "type": "object",
            "properties": {
                "deletedFiles": {
                    "type": "integer"
                },
                "durationMs": {
                    "type": "integer"
                },
                "finishedAt": {
                    "type": "string"
                },
                "freedBytes": {
                    "type": "integer"
                },
                "targetStatus": {
                    "type": "string"
                },
                "triggerReason": {
                    "description": "\"watermark\", \"scheduled\", \"manual\"",
                    "type": "string"
                }
            }
        },
        "storage.PathTestRequest": {
            "type": "object",
            "required": [
                "path"
            ],
            "properties": {
                "path": {
                    "type": "string"
                }
            }
        },
        "storage.PathTestResponse": {
            "type": "object",
            "properties": {
                "deviceId": {
                    "type": "integer"
                },
                "errorReason": {
                    "type": "string"
                },
                "exists": {
                    "type": "boolean"
                },
                "freeBytes": {
                    "type": "integer"
                },
                "fsType": {
                    "type": "string"
                },
                "isExternal": {
                    "type": "boolean"
                },
                "isMount": {
                    "type": "boolean"
                },
                "mountPoint": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "totalBytes": {
                    "type": "integer"
                },
                "writable": {
                    "type": "boolean"
                }
            }
        },
        "storage.StorageConfig": {
            "type": "object",
            "properties": {
                "emergencyStopMinMb": {
                    "description": "Emergency minimum free space in megabytes (100..102400)",
                    "type": "integer"
                },
                "emergencyStopPercent": {
                    "description": "Emergency write-stop percentage (90..99)",
                    "type": "integer"
                },
                "exportsRetentionHours": {
                    "description": "Exported clips retention in hours (1..168)",
                    "type": "integer"
                },
                "highWatermarkPercent": {
                    "description": "High watermark percentage triggering cleaner (50..95)",
                    "type": "integer"
                },
                "lowWatermarkPercent": {
                    "description": "Low watermark percentage where cleaner sleeps (40..85)",
                    "type": "integer"
                },
                "mediaDirectory": {
                    "description": "Root media path, e.g. \"/mnt/storage/media\"",
                    "type": "string"
                },
                "recordingsRetentionDays": {
                    "description": "Video recordings retention in days (1..365)",
                    "type": "integer"
                },
                "snapshotsRetentionDays": {
                    "description": "Snapshot captures retention in days (1..730)",
                    "type": "integer"
                }
            }
        },
        "storage.StorageHealthStatus": {
            "type": "string",
            "enum": [
                "healthy",
                "warning",
                "cleaning",
                "emergency_stopped",
                "error"
            ],
            "x-enum-comments": {
                "StatusCleaning": "Background cleaner is actively pruning expired/stale files",
                "StatusEmergencyStopped": "Storage touched critical emergency line; writes suspended",
                "StatusError": "Path missing, read-only, or external disk unmounted/fallen through",
                "StatusHealthy": "Storage has plenty of space and read/write is normal",
                "StatusWarning": "Storage usage touched high watermark threshold"
            },
            "x-enum-descriptions": [
                "Storage has plenty of space and read/write is normal",
                "Storage usage touched high watermark threshold",
                "Background cleaner is actively pruning expired/stale files",
                "Storage touched critical emergency line; writes suspended",
                "Path missing, read-only, or external disk unmounted/fallen through"
            ],
            "x-enum-varnames": [
                "StatusHealthy",
                "StatusWarning",
                "StatusCleaning",
                "StatusEmergencyStopped",
                "StatusError"
            ]
        },
        "storage.StorageStatus": {
            "type": "object",
            "properties": {
                "breakdown": {
                    "description": "Categorized usage breakdown",
                    "allOf": [
                        {
                            "$ref": "#/definitions/storage.StorageUsageBreakdown"
                        }
                    ]
                },
                "canWrite": {
                    "description": "True if storage is currently accepting new writes",
                    "type": "boolean"
                },
                "deviceId": {
                    "description": "Associated filesystem device ID (st_dev)",
                    "type": "integer"
                },
                "freeBytes": {
                    "description": "Available capacity for non-root users in bytes",
                    "type": "integer"
                },
                "fsType": {
                    "description": "Filesystem type, e.g. \"ext4\", \"xfs\", \"btrfs\"",
                    "type": "string"
                },
                "isExternal": {
                    "description": "True if mounted on dedicated volume outside rootfs (/)",
                    "type": "boolean"
                },
                "mediaDirectory": {
                    "description": "Currently active media directory",
                    "type": "string"
                },
                "mountPoint": {
                    "description": "Mount point where the media directory lives",
                    "type": "string"
                },
                "status": {
                    "description": "Current health status",
                    "allOf": [
                        {
                            "$ref": "#/definitions/storage.StorageHealthStatus"
                        }
                    ]
                },
                "totalBytes": {
                    "description": "Total capacity in bytes",
                    "type": "integer"
                },
                "updatedAt": {
                    "description": "Metric collection timestamp (UTC)",
                    "type": "string"
                },
                "usagePercent": {
                    "description": "Volume usage percentage (0..100)",
                    "type": "integer"
                },
                "usedBytes": {
                    "description": "Used capacity in bytes",
                    "type": "integer"
                }
            }
        },
        "storage.StorageUsageBreakdown": {
            "type": "object",
            "properties": {
                "exportsBytes": {
                    "description": "Total size of temporary exported files in bytes",
                    "type": "integer"
                },
                "otherBytes": {
                    "description": "Other files residing on the same filesystem/volume",
                    "type": "integer"
                },
                "recordingsBytes": {
                    "description": "Total size of video recordings in bytes",
                    "type": "integer"
                },
                "snapshotsBytes": {
                    "description": "Total size of AI snapshots in bytes",
                    "type": "integer"
                }
            }
        },
        "storage.UpdateConfigRequest": {
            "type": "object",
            "required": [
                "emergencyStopMinMb",
                "emergencyStopPercent",
                "exportsRetentionHours",
                "highWatermarkPercent",
                "lowWatermarkPercent",
                "mediaDirectory",
                "recordingsRetentionDays",
                "snapshotsRetentionDays"
            ],
            "properties": {
                "emergencyStopMinMb": {
                    "type": "integer",
                    "maximum": 102400,
                    "minimum": 100
                },
                "emergencyStopPercent": {
                    "type": "integer",
                    "maximum": 99,
                    "minimum": 90
                },
                "exportsRetentionHours": {
                    "type": "integer",
                    "maximum": 168,
                    "minimum": 1
                },
                "highWatermarkPercent": {
                    "type": "integer",
                    "maximum": 95,
                    "minimum": 50
                },
                "lowWatermarkPercent": {
                    "type": "integer",
                    "maximum": 85,
                    "minimum": 40
                },
                "mediaDirectory": {
                    "type": "string"
                },
                "recordingsRetentionDays": {
                    "type": "integer",
                    "maximum": 365,
                    "minimum": 1
                },
                "snapshotsRetentionDays": {
                    "type": "integer",
                    "maximum": 730,
                    "minimum": 1
                }
            }
        },
        "systemtime.ManualTimeRequest": {
            "type": "object",
            "required": [
                "targetTime"
            ],
            "properties": {
                "targetTime": {
                    "type": "string"
                }
            }
        },
        "systemtime.RtcStatus": {
            "type": "string",
            "enum": [
                "normal",
                "missing",
                "error"
            ],
            "x-enum-varnames": [
                "RtcStatusNormal",
                "RtcStatusMissing",
                "RtcStatusError"
            ]
        },
        "systemtime.SyncStatus": {
            "type": "object",
            "properties": {
                "errorMessage": {
                    "type": "string"
                },
                "lastSyncServer": {
                    "type": "string"
                },
                "lastSyncTime": {
                    "type": "string"
                },
                "offsetMs": {
                    "type": "number"
                },
                "rttMs": {
                    "type": "number"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "systemtime.SystemTimeStatus": {
            "type": "object",
            "properties": {
                "currentTime": {
                    "type": "string"
                },
                "hasPermission": {
                    "type": "boolean"
                },
                "mode": {
                    "type": "string"
                },
                "ntpServers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "rtcStatus": {
                    "$ref": "#/definitions/systemtime.RtcStatus"
                },
                "syncIntervalSeconds": {
                    "type": "integer"
                },
                "syncStatus": {
                    "$ref": "#/definitions/systemtime.SyncStatus"
                },
                "timezone": {
                    "type": "string"
                }
            }
        },
        "systemtime.UpdateConfigRequest": {
            "type": "object",
            "required": [
                "mode",
                "ntpServers",
                "syncIntervalSeconds",
                "timezone"
            ],
            "properties": {
                "mode": {
                    "type": "string",
                    "enum": [
                        "ntp",
                        "manual"
                    ]
                },
                "ntpServers": {
                    "type": "array",
                    "maxItems": 5,
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                },
                "syncIntervalSeconds": {
                    "type": "integer",
                    "maximum": 86400,
                    "minimum": 60
                },
                "timezone": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Zhulong API",
	Description:      "Local API for the Zhulong edge operations host.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
